### ISSUE TITLE
weather command - TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Positive2022** [tovade/Andoi#5]
the error is with the node module however 
the error is:  ```TypeError: Cannot read property 'length' of undefined
    at /home/container/commands/Utils/weather.js:22:20
    at /home/container/node_modules/weather-js/index.js:59:18
    at Parser.<anonymous> (/home/container/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:315:20)
    at SAXParser.onclosetag (/home/container/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/container/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/container/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/container/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/container/node_modules/sax/lib/sax.js:1293:13)
    at Parser.exports.Parser.Parser.parseString (/home/container/node_modules/xml2js/lib/parser.js:323:31)
Emitted 'error' event on Parser instance at:
    at Parser.exports.Parser.Parser.parseString (/home/container/node_modules/xml2js/lib/parser.js:327:16)
    at Parser.parseString (/home/container/node_modules/xml2js/lib/parser.js:5:59)
    at Request._callback (/home/container/node_modules/weather-js/index.js:55:17)
    at Request.self.callback (/home/container/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/container/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/container/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)```
but it leads to bot crash
this error happened when i typed: `!weather head`

**Comment by tovade** [comment]
this is fixed
